annotations:
  licenses: MIT
apiVersion: v2
appVersion: 0.10.0
version: 0.1.0
name: timeoff-management-application
description: "Web application for managing employee absences."
home: https://github.com/timeoff-management/timeoff-management-application
icon: https://timeoff.management/images/trademark.svg
maintainers:
  - email: joseph.oyomi11@gmail.com
    name: joeyomi
    url: https://github.com/joeyomi
sources:
  - https://github.com/joeyomi/timeoff-management-application.git
  - https://github.com/timeoff-management/timeoff-management-application.git
dependencies:
  - name: helmet
    version: ^0
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
keywords:
  - timeoff-management-application
